
echo Generating source for loading core functionality and extensions...
ruby glelcg-xml.rb -l -f extensions.txt -u .. gl.xml glext_windows

echo Generating source for loading WGL extensions...
ruby glelcg-xml.rb -l -f wgl_extensions.txt -u .. wgl.xml wglext
